name: 🙋‍♂️ [QuickRSS] - 支持与反馈
description: "获取有关 QuickRSS、报告错误或请求功能的帮助。"
title: '🙋‍♂️ 支持与反馈: QuickRSS'
labels: ['support', 'feedback', 'question']
body:
  - type: markdown
    attributes:
      value: |
        <img align="right" height="100" alt="QuickRSS" src="https://github.com/user-attachments/assets/e1d9f76f-0f3d-4ba5-8a15-253ee173bb1c" /> 
        
        「Quick RSS」是一款简单易用、私密且功能直观的桌面 RSS 订阅阅读器应用，无论你是资讯狂热者，还是喜欢跟进博客文章、新闻头条，Quick RSS 都能帮助你轻松管理和阅读你喜爱的 RSS 订阅源。

  - type: textarea
    attributes:
      label: 🙋‍♂️ 您需要什么帮助？
      description: 描述您面临的问题或您想要请求的功能。
      placeholder: 例如，我遇到了问题...
    validations:
      required: true

  - type: input
    attributes:
      label: "💻 桌面"
      description: 您的操作系统和版本。
      placeholder: 例如，`macOS 14.0.1`

  - type: markdown
    attributes:
      value: |
        **如何向我发送应用程序的崩溃报告？**

        - 在 macOS 上打开 Finder
        - 从“前往”菜单中选择 **前往文件夹…** <kbd>⇧</kbd> + <kbd>⌘</kbd> + <kbd>G</kbd>
        - 输入：**~/Library/Logs/DiagnosticReports**
        - 在出现的列表中，选择所有以应用程序名称开头的文件，将它们压缩成 ZIP 文件并发送给我
        - 将文件附加到此问题中

  - type: textarea
    attributes:
      label: ℹ️ 补充说明
      description: 在此添加有关问题的其他上下文信息。
      placeholder: 例如：截图、复现步骤等。
    validations:
      required: false