name: 🙋‍♂️ [QuickRSS] - Support & Feedback
description: Get help with QuickRSS, report bugs, or request features.
title: '🙋‍♂️ Support & Feedback: Quick RSS'
labels: ['support', 'feedback', 'question']
assignees:
  - jaywcjlove
body:
  - type: markdown
    attributes:
      value: |
        <img align="right" height="86" alt="QuickRSS" src="https://github.com/user-attachments/assets/3e694247-ad5c-4ac8-a4ae-8b89352324d4"> Please provide as much detail as possible about your support request or feedback.

        Make sure you are on the latest version and try to restart your device. If the app crashed (macOS-only), it would be very helpful if you could include a crash report.
        

  - type: textarea
    attributes:
      label: 🙋‍♂️ What do you need help with?
      description: Describe the issue or feedback you have for Quick RSS.
      placeholder: ex. I have trouble configuring the RSS feed or I want to suggest a new feature.
    validations:
      required: true

  - type: dropdown
    id: os_version
    attributes:
      label: "💻 Desktop"
      description: Your operating system and version.
      options:
        - macOS 15.0 (Sequoia)
        - macOS 14.0 (Sonoma)
        - iOS 18.0
        - iOS 17.0
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **How can I send you a crash report for one of your apps?**

        - macOS Open Finder
        - Select Go to **Folder…** from the Go menu <kbd>⇧</kbd> + <kbd>⌘</kbd> + <kbd>G</kbd>
        - Enter: **~/Library/Logs/DiagnosticReports**
        - In the resulting list, select all files that starts with the app name, ZIP them, and send me
        - Attach the file to this issue


  - type: textarea
    attributes:
      label: ℹ️ Additional context
      description: Add any additional information that could be helpful.
      placeholder: ex. Screenshots, steps to reproduce, etc.
    validations:
      required: false